pipeline {
    // agent any
    agent {label 'linux'}
    environment {
        AWS_ACCOUNT_ID="009570627831"
        AWS_DEFAULT_REGION="eu-central-1" 
        IMAGE_REPO_NAME="node"
        IMAGE_TAG="17.4-alpine"
        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}"
    }
   
    stages {
        
         stage('Logging into AWS ECR') {
            steps {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'petrugiurca-aws-creds', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {  
                    script {
                        sh '''
                            aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
                        '''    
                
                    }  
                }
            }
        }
        
        stage('Building image') {
            steps{
                script {
                    dockerImage = docker.build "${IMAGE_REPO_NAME}:${IMAGE_TAG}"
                }
            }
        }
        
        stage('Pushing to ECR') {
            steps{  
                script {
                    sh "docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:$IMAGE_TAG"
                    sh "docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}"
                }
            }
        }
    }
    post {
        always {
            echo 'One way or another, I have finished!'
        }
        success {
            echo 'I succeeded!'
        }
        failure {
            echo 'Failed pushing the image!'
        }
    }  
}